### ISSUE TITLE
Deprecated function use function: load_data instead

### ISSUE THREAD

**Issue by xiaozialei** [oarriaga/single_shot_multibox_detector#2]
/home/mkyuan/anaconda2/bin/python /home/mkyuan/single_shot_multibox_detector/src/train.py
Using TensorFlow backend.
Deprecated function use function: load_data instead
Traceback (most recent call last):
  File "/home/mkyuan/single_shot_multibox_detector/src/train.py", line 38, in <module>
    model = SSD300(image_shape, num_classes, weights_path, frozen_layers)
  File "/home/mkyuan/single_shot_multibox_detector/src/models/ssd.py", line 340, in SSD300
    model.load_weights(weights_path, by_name=True)
  File "/home/mkyuan/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2489, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/mkyuan/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/mkyuan/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/home/ilan/minonda/conda-bld/work/h5py/h5f.c:1942)
IOError: Unable to open file (File signature not found)

Process finished with exit code 1

Current keras/tensroflow versions I am using are 2.0.2/1.1.0.  I have encountered a problem that seems to be related to weights_SSD300.hdf5.  I find the size of weights_SSD300.hdf5 in trained_model directory is 0KB.

**Comment by oarriaga** [comment]
You can find a new set of weights in this repository https://github.com/rykov8/ssd_keras
